### ISSUE TITLE
Text is mirrored (invert)

### ISSUE THREAD

**Issue by el20b014** [afiskon/stm32-ssd1351#1]
Houston,

we have a problem.
Our Display shows us the Text mirrored. But we tried everything to get it right. Well it didn't worked. Can you help us?
What do we have to change?

**Comment by afiskon** [comment]
I guess you have to modify the initialization sequence for your display somewhere around here https://github.com/afiskon/stm32-ssd1351/blob/master/Lib/ssd1351/ssd1351.c#L127 Try changing the value from 0xA6 (NORMALDISPLAY) to 0xA7 (INVERTDISPLAY).

**Comment by Davi512** [comment]
Hi, have similar issue
![Uploading IMG_9794.jpeg…]()

**Comment by Davi512** [comment]
![IMG_9780](https://github.com/afiskon/stm32-ssd1351/assets/113210366/546a2414-3e7c-4f8d-80b2-53d550e6819b)

**Comment by Davi512** [comment]
And this 
![IMG_9794](https://github.com/afiskon/stm32-ssd1351/assets/113210366/51c84c47-adf1-4ea6-a9e3-aca42ca3f4fc)

**Comment by afiskon** [comment]
@Davi512 did you try the fix proposed above? Did it work for you?

**Comment by Davi512** [comment]
I dont understand. Today is working without any issue

**Comment by afiskon** [comment]
Well I don't have a problematic device on hands in order to do anything about this. If you'll figure this out please submit a patch.
