### ISSUE TITLE
Image inverted

### ISSUE THREAD

**Issue by Davi512** [afiskon/stm32-ssd1351#2]
Tried to change from A7 to A6, nothing happened 
![Uploading IMG_9794.jpeg…]()

**Comment by Davi512** [comment]
![IMG_9794](https://github.com/afiskon/stm32-ssd1351/assets/113210366/8bb71782-0f21-42ca-bb33-3c5cf67d29f6)

**Comment by afiskon** [comment]
@Davi512 this was reported before. Unfortunately I don't have a module with such a behavior. Apparently some of them invert the image, some don't. If you will be able to figure out where the problem is please submit a corresponding patch.

**Comment by afiskon** [comment]
Closing as a duplicate of https://github.com/afiskon/stm32-ssd1351/issues/1

**Comment by Davi512** [comment]
Ok, will try to figure it out. Before I tried on arduino adafruit lib and work
